Update pr_diff.yml

diff --git a/.github/workflows/pr_diff.yml b/.github/workflows/pr_diff.yml
--- a/.github/workflows/pr_diff.yml
+++ b/.github/workflows/pr_diff.yml
@@ -1,4 +1,4 @@
-name: Send PR and Check for "hello"
+name: Send PR and Check for "hello msg"
 
 on:
   pull_request:
@@ -16,24 +16,36 @@ jobs:
       - name: Get PR Diff
         id: get_pr_diff
         run: |
-          PR_DIFF=$(curl -s "${{ github.event.pull_request.diff_url }}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}")
-          echo "PR_DIFF<<EOF" >> $GITHUB_ENV
-          echo "$PR_DIFF" >> $GITHUB_ENV
-          echo "EOF" >> $GITHUB_ENV
+          echo "Fetching PR diff..."
+          curl -s "${{ github.event.pull_request.diff_url }}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" > pr_diff.txt
+          echo "PR diff content fetched."
 
-      - name: Send PR information to FlaskAPI
+      - name: Send PR data to FlaskAPI
         id: send_pr_info
         run: |
+          echo "Sending PR information to FlaskAPI..."
           API_URL="https://chatty-nails-reply.loca.lt/workflows"
           PR_DETAILS=$(echo "{\"diff_url\": \"${{ github.event.pull_request.diff_url }}\", \"number\": \"${{ github.event.pull_request.number }}\", \"repo\": \"${{ github.event.repository.name }}\", \"owner\": \"${{ github.event.pull_request.user.login }}\", \"github_token\": \"${{ secrets.GITHUB_TOKEN }}\", \"head_sha\": \"${{ github.event.pull_request.head.sha }}\"}")
-          response=$(curl -X POST -H "Content-Type: application/json" -d "$PR_DETAILS" "$API_URL")
-          echo "response=$response" >> $GITHUB_ENV
+          RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d "$PR_DETAILS" "$API_URL")
+          echo "API response: $RESPONSE"
+          echo "response=$RESPONSE" >> $GITHUB_ENV
 
-      - name: Wait for FlaskAPI response
+      - name: Wait for FlaskAPI response datas
         id: wait_for_response
         run: echo "Waiting for FlaskAPI response..."
 
-      - name: Print response
+      - name: Print response data
         run: echo "The response is ${{ env.response }}"
+
+      - name: Check for "hello" in PR diff
+        run: |
+          if grep -q "hello" pr_diff.txt; then
+            echo "PR diff contains 'hello'"
+            # Optionally, you can fail the job or take other actions
+            exit 1
+          else
+            echo "PR diff does not contain 'hello'"
+          fi
+
 
       
